# seek controls
l seek 3
h seek -3
j seek -60
k seek 60
RIGHT       seek 5 exact
LEFT        seek -5 exact


S cycle sub # subtitle controls
alt+s playlist-shuffle

# volume controls
AXIS_UP    add volume 2
AXIS_DOWN  add volume -2
UP  add volume 2
DOWN add volume -2
MOUSE_BTN3 add volume 2
MOUSE_BTN4 add volume -2


# rotation controls
r cycle-values video-rotate 270 180 90 0
t cycle-values video-rotate 90 180 270 0

# playlist display
ctrl+p show-text "${playlist}"

# speed adjustment
| add speed 1


# aspect ratio toggle
F2 cycle_values video-aspect "16:9" "16:10" "4:3" "2.35:1" "-1"

# progress bar controls
. script-binding progressbar/step-forward
, script-binding progressbar/step-backward
C script-binding progressbar/toggle-inactive-bar
mouse_btn0 script-binding progressbar/left-click
tab script-binding skip-key



# play list view with thumbnail
g script-message contact-sheet-close; script-message playlist-view-toggle
c script-message playlist-view-close; script-message contact-sheet-toggle

# subtitle scaling
 ALT+k add sub-scale +0.1 # increase subtitle font size
 ALT+j add sub-scale -0.1 # decrease subtitle font size


# thumbnail generation
shift+alt+s script-binding generate-thumbnails


# for anime4k shaders
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_M.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A (Fast)"
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode B (Fast)"
CTRL+3 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode C (Fast)"
CTRL+4 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_M.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl;~~/shaders/Anime4K_Restore_CNN_S.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A+A (Fast)"
CTRL+5 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Restore_CNN_Soft_S.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode B+B (Fast)"
CTRL+6 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Restore_CNN_S.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode C+A (Fast)"
CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"


# audio processi
F1 cycle-values af "bass=f=210:g=-17.7" "loudnorm=linear=no" "dynaudnorm=s=0" ""  # Volume normalization and bass tuning
F2 cycle-values af "acompressor=knee=1.4:detection=peak:ratio=18:threshold=.04:makeup=2.38" "compand=attacks=0:points=-80/-900|-45/-15:gain=1" ""
F3 cycle-values af ""  # Reset audio filtersng filters
