deband=no
osc=no
border=no
scale=ewa_lanczossharp
cscale=ewa_lanczossharp

hwdec=vaapi
hwdec-codecs=all
interpolation=no
tscale=oversample
volume=50
volume-max=200
video-sync=audio
# video-sync=display-resample
hr-seek-framedrop=yes # bitrate videos seek


autofit-larger=100%x95%
keep-open=yes
cache-secs=4.0
# save-position-on-quit


osd-playing-msg=${media-title}
player-operation-mode=pseudo-gui
osd-font-size=35
osd-color="#FFFFFFFF"
osd-border-color="#FF262626"
osd-border-size=2
osd-shadow-offset=1.5
osd-shadow-color="#88000000"
osd-spacing=0.5
term-osd-bar  
cursor-autohide=1000 
prefetch-playlist=yes
force-seekable=yes



#############
# Subtitles #
#############

embeddedfonts=yes # use embedded fonts for SSA/ASS subs
sub-font="Cartograph CF"
sub-font-size=36
sub-color="#FFFFFFFF"
sub-border-color="#FF262626"
sub-border-size=3.2
sub-shadow-offset=1
sub-shadow-color="#33000000"
sub-spacing=0.5

#########
# Audio #
#########
ao=pulse

###############
# Screenshots #
###############
screenshot-template="%x/Screens/Screenshot-%F-T%wH.%wM.%wS.%wT-F%{estimated-frame-number}"
screenshot-format=png # Set screenshot format
screenshot-png-compression=0 # Range is 0 to 10. 0 being no compression.
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes # Same output bitdepth as the video
screenshot-directory=Pictures/

[pyradio]
volume=50
