Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.usb-GeneralPlus_USB_Audio_Device-00.mono-fallback"
LastUsedOutput = ""
