
[greenclip]
  history_file = "/home/romjan/.cache/greenclip.history"
  blacklisted_applications = []
  enable_image_support = true
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 80
  max_selection_size_bytes = 0
  trim_space_from_selection = true
  static_history = [""]
  use_primary_selection_as_input = false
